#!/bin/bash

function deploy_basename {
  local cmd="$(basename "$1")"; shift
  echo "${cmd#aoh-}"
} 

# define command line options:
#   var name, default, description, short option
DEFINE_string "gateway" "" "deploy gateway host" "G"
DEFINE_boolean "proxy" "$FLAGS_FALSE" "use a gateway to proxy deploys" "p"
DEFINE_boolean "direct" "$FLAGS_FALSE" "override proxy" "d"
DEFINE_string "chef" "" "location to chef repo with opsdb" "c"
DEFINE_string "tag" "HEAD" "tag to deploy in production" "t"
DEFINE_string "user" "" "app user override" "u"
DEFINE_string "group" "" "app group override" "g"
DEFINE_string "ssh_login" "" "ssh login override" "l"
DEFINE_boolean "migrations" "$FLAGS_FALSE" "run development migrations" "M"
DEFINE_string "reviewer" "" "who has reviewed the production version" "R"
DEFINE_boolean "debug" "${FLAGS_debug:-$FLAGS_FALSE}" "turn on debugging" "D"

# entry point
function main {
  export _AO_ARGS="$@"

  if [[ "$#" = 0 ]]; then
    logger_fatal "must specify a pod name or integration environment when deploying"
    exit 1
  fi

  if [[ -n "$FLAGS_user" ]]; then
    export _AO_USER="$FLAGS_user"
  fi

  : ${_AO_DEPLOYER:=$LOGNAME}
  export _AO_DEPLOYER

  if [[ -n "$FLAGS_group" ]]; then
    export _AO_GROUP="$FLAGS_group"
  fi

  if [[ -n "$FLAGS_chef" ]]; then
    export _AO_CHEF="$FLAGS_chef"
  fi

  if [[ -n "$FLAGS_gateway" ]]; then
    export GATEWAY="$FLAGS_gateway"
  fi

  if [[ -n "$FLAGS_debug" ]]; then
    export FLAGS_debug
  fi

  if [[ "$FLAGS_proxy" = "$FLAGS_FALSE" || "$FLAGS_direct" = "$FLAGS_TRUE" || -z "$FLAGS_gateway" ]]; then
    export _AO_DEPLOY=1

    bundle check 2>&1 >/dev/null || { bundle install --quiet --local --path vendor/bundle $_AO_EXTRA_BUNDLER_ARGS || bundle check > /dev/null; }

    if [[ "$FLAGS_migrations" = "$FLAGS_TRUE" ]]; then
      export FLAGS_migrations
    fi

    if [[ -n "$FLAGS_tag" ]]; then
      export FLAGS_tag
    fi

    if [[ -n "$FLAGS_reviewer" ]]; then
      export FLAGS_reviewer
    fi

    aomain "$@"
  else 
    if [[ "$#" > 0 ]]; then
      case "$1" in
        production)
          if [[ -z "$FLAGS_tag" || "$FLAGS_tag" = "HEAD" ]]; then
            case "$(deploy_basename $0)" in
              hosts|debug|dna)
                true
                ;;
              *)
                logger_fatal "must specify a version using --tag|-t"
                exit 1
                ;;
            esac
          fi
          ;;
      esac
    fi

    local gateway="$FLAGS_gateway"
    if [[ -n "$FLAGS_ssh_login" ]]; then
      gateway="${FLAGS_ssh_login}@${gateway}"
    fi

    $shome/sbin/proxy "$gateway" "$FLAGS_tag" $(deploy_basename $0) ${_AO_USER_ARGS}
  fi
}
